import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from "./_lib/styledComponentsRegistry";
import RecoilSetting from "./_lib/recoilSetting";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <RecoilSetting>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </RecoilSetting>
      </body>
    </html>
  );
}
