import type { Metadata } from "next";
import "./globals.css";
import LibrarySettings from "./_lib/librarySettings";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <LibrarySettings>{children}</LibrarySettings>
      </body>
    </html>
  );
}
